### ISSUE TITLE
NeogeoCD and PC Engine CD issue BG

### ISSUE THREAD

**Issue by redinou** [c64-dev/es-epicnoir#11]
Hi,
Love this theme a lot!! 
Good job on that. but I have an issue, the neogeo CD and PC Engine CD background is black without any images or texts :(.

**Comment by c64-dev** [comment]
Have you resolved this redinou?
I have doublechecked and on my system they show up ok.

**Comment by redinou** [comment]
I fixed it by download it directly from the RetroPie setup^^.

The manual one via FTP was messing with my system^^
It's all good now.
 Thank you!!!!!
