### ISSUE TITLE
Additional systems / libraries

### ISSUE THREAD

**Issue by iwubcode** [c64-dev/es-epicnoir#2]
This is great!

Please add the following additional system / libraries:

- Nintendo Switch
- Nintendo Wiiware (technically a part of "Wii" but many themes have it as a separate system)
- Sony PS3
- Nintendo 3DS

**Comment by c64-dev** [comment]
Thanks for the nice comments! 

Requests for additional themes can be made on the theme's main thread here: https://retropie.org.uk/forum/topic/25351/epic-noir-dark-mode-theme

Also keep in mind that you can easily change whichever of the existing systems you don't need to the systems you require. 

Simply do the following:
* Rename the system folders on the main theme folder to reflect the new systems, **for example** :
`atari800 --> switch`
`atari2600 --> wiiware`
`atari5800 --> sps3`
`3do --> 3ds`
* Edit the xml files inside the newly named system folders as needed (System name and info)
* Repeat the renaming process inside the _art folder, for the `controllers,` `indicators` and `posters` folders.

After that the theme should show the required systems.
