### ISSUE TITLE
Adding systems

### ISSUE THREAD

**Issue by markb44z** [c64-dev/es-epicnoir#6]
Any plans to add Pokemon Mini and Super Gameboy as they're currently blank on ArkOS on the RG351M? Thanks!

**Comment by c64-dev** [comment]
Hi,

One of the best things about ES themes is that they are open-ended, alowing users to add (or remove) their own systems as they see fit. As such, we couldn't realistically account for all the available consoles and home systems out there, so it's inevitable that there will be systems missing along the way. 

To solve your issue locally, you can easily create a new system, or even easier change an unused system to the ones you need, replacing the text information and system's image to whatever you want. If you require more information on how to do this please let me know.
