### ISSUE TITLE
Crashes on boot

### ISSUE THREAD

**Issue by dbasinge** [c64-dev/es-epicnoir#9]
After install epicnoir and switching to it, it will crash ES to crash, same thing happens on boot.

**Comment by vradinolfi** [comment]
I know this is old but just in case anyone else is having the same issue - I did a bit of troubleshooting and finally found that by specifying a 1080p/720p resolution in the launch options I finally got this theme to work for me. for example, my emulationstation shortcut reads as follows:

`"C:\Program Files (x86)\EmulationStation\emulationstation.exe" --resolution 1920 1080`

**Comment by SoFLazerTag** [comment]
> I know this is old but just in case anyone else is having the same issue - I did a bit of troubleshooting and finally found that by specifying a 1080p/720p resolution in the launch options I finally got this theme to work for me. for example, my emulationstation shortcut reads as follows:
> 
> `"C:\Program Files (x86)\EmulationStation\emulationstation.exe" --resolution 1920 1080`

Thank you! Never would have considered this issue to be about the display res

**Comment by c64-dev** [comment]
Thank you Vradinolfi. Marking as solved
